import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar configuration for the Physical AI & Humanoid Robotics book
  docsSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Module 1 - The Robotic Nervous System (ROS 2)',
      items: [
        'modules/ros2-nervous-system/fundamentals',
        'modules/ros2-nervous-system/nodes-topics-services',
        'modules/ros2-nervous-system/urdf-modeling',
      ],
    },
    {
      type: 'category',
      label: 'Module 2 - The Digital Twin (Gazebo & Unity)',
      items: [
        'modules/digital-twin/gazebo-physics',
        'modules/digital-twin/unity-digital-twins',
        'modules/digital-twin/sensor-simulation',
      ],
    },
    {
      type: 'category',
      label: 'Module 3 - The AI-Robot Brain (NVIDIA Isaac)',
      items: [
        'modules/ai-robot-brain/isaac-sim',
        'modules/ai-robot-brain/isaac-ros-vslam',
        'modules/ai-robot-brain/nav2-navigation',
      ],
    },
    {
      type: 'category',
      label: 'Module 4 - Vision-Language-Action (VLA)',
      items: [
        'modules/vla/voice-to-action',
        'modules/vla/llm-planning',
        'modules/vla/capstone-autonomous-humanoid',
      ],
    },
  ],
};

export default sidebars;
